# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ZomatoApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'Nuke'
  pod 'Reusable'
  pod "SkeletonView"
  pod 'GoogleMaps'
  pod 'GooglePlaces'

  # Pods for ZomatoApp

end
